-- USER SQL
CREATE USER SM IDENTIFIED BY SM 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "RESOURCE" TO SM;
GRANT "CONNECT" TO SM;

-- sm_user table
--DROP TABLE SM.SM_USER CASCADE CONSTRAINTS;
CREATE TABLE "SM"."SM_USER"
  (
    "SM_USER_ID"  NUMBER(10) NOT NULL ENABLE,
    "USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "PASSWORD" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "ROLE_ID" VARCHAR2(10),
    "EMAIL" VARCHAR2(50),
    "STATUS" VARCHAR2(10) NOT NULL,
    CONSTRAINT "SM_USER_PK" PRIMARY KEY ("SM_USER_ID") 
  );
  
CREATE UNIQUE INDEX "SM"."SM_USER_UNX_IND" ON "SM"."SM_USER" ("USERNAME");

-- student table::
--DROP TABLE SM.SM_STUDENT CASCADE CONSTRAINTS;
CREATE TABLE "SM"."SM_STUDENT"
  (
    "SM_STUDENT_ID"  NUMBER(10) NOT NULL ENABLE,
    "FIRST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "LAST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "PHONE_NUMBER" VARCHAR2(20),
    "EMAIL" VARCHAR2(50),
    "ADDRESS" VARCHAR2(100),
    CONSTRAINT "SM_STUDENT_PK" PRIMARY KEY ("SM_STUDENT_ID") 
  );

-- insert default data 
INSERT INTO SM_USER (SM_USER_ID,USERNAME,PASSWORD,ROLE_ID,EMAIL,STATUS) VALUES (1,'admin','JGL25BVBBBW96QI9TE4V37FNQCHZ/EU4QB9VKRRIQRG=',null,'pvnbk2006@gmail.com','ACTIVE');
  
-- sequences
CREATE SEQUENCE SM.SM_USER_SEQ INCREMENT BY 1 START WITH 1000 MAXVALUE 1000000000 MINVALUE 1000 NOCACHE;
CREATE SEQUENCE SM.SM_STUDENT_SEQ INCREMENT BY 1 START WITH 1000 MAXVALUE 1000000000 MINVALUE 1000 NOCACHE;
  