//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.13 at 09:41:37 PM PDT 
//


package com.vietnamarena.xml.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="termsofService" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="features">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="feature" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="location">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country_iso3166" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tz_short" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tz_long" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="lon" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="magic" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="wmo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="l" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="requesturl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wuiurl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="nearby_weather_stations">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="airport">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="station">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="icao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="lon" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="pws" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="current_observation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="image">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="display_location">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="full" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="state_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="country_iso3166" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="magic" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="wmo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="elevation" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="observation_location">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="full" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="country_iso3166" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="elevation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="estimated" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="station_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="observation_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="observation_time_rfc822" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="observation_epoch" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="local_time_rfc822" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="local_epoch" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="local_tz_short" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="local_tz_long" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="local_tz_offset" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="weather" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="temperature_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="temp_f" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="temp_c" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="relative_humidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wind_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wind_dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wind_degrees" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="wind_mph" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="wind_gust_mph" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="wind_kph" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="wind_gust_kph" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="pressure_mb" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="pressure_in" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="pressure_trend" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="dewpoint_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dewpoint_f" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="dewpoint_c" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="heat_index_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="heat_index_f" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="heat_index_c" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="windchill_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="windchill_f" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="windchill_c" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="feelslike_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="feelslike_f" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="feelslike_c" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="visibility_mi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="visibility_km" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="solarradiation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UV" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="precip_1hr_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="precip_1hr_in" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="precip_1hr_metric" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="precip_today_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="precip_today_in" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="precip_today_metric" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="icon" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="icon_url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="forecast_url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="history_url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="ob_url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "termsofService",
    "features",
    "location",
    "currentObservation"
})
@XmlRootElement(name = "response")
public class WeatherResponse {

    protected float version;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String termsofService;
    @XmlElement(required = true)
    protected Features features;
    @XmlElement(required = true)
    protected Location location;
    @XmlElement(name = "current_observation", required = true)
    protected CurrentObservation currentObservation;

    /**
     * Gets the value of the version property.
     * 
     */
    public float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(float value) {
        this.version = value;
    }

    /**
     * Gets the value of the termsofService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsofService() {
        return termsofService;
    }

    /**
     * Sets the value of the termsofService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsofService(String value) {
        this.termsofService = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link Features }
     *     
     */
    public Features getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link Features }
     *     
     */
    public void setFeatures(Features value) {
        this.features = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the currentObservation property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentObservation }
     *     
     */
    public CurrentObservation getCurrentObservation() {
        return currentObservation;
    }

    /**
     * Sets the value of the currentObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentObservation }
     *     
     */
    public void setCurrentObservation(CurrentObservation value) {
        this.currentObservation = value;
    }

}
